networks:
  test-network:
    driver: bridge
    attachable: true

services:
  server:
    image: openquantumsafe/nginx
    hostname: server.com
    ports:
      - "4433:4433"
    networks:
      - test-network
    volumes:
      - ./server/certs/:/opt/nginx/pki

  server_quantumonly:
    image: openquantumsafe/nginx
    hostname: server_quantum.com
    ports:
      - "4443:4443"
    networks:
      - test-network
    volumes:
      - ./server_quantumonly/certs/:/opt/nginx/pki
      - ./server_quantumonly/config/:/opt/nginx/nginx-conf
  
  openssl_client:
    image: openquantumsafe/curl
    networks:
      - test-network
    volumes:
      - ./openssl_client/ca/:/opt/tmp
  
  boringssl_client:
    image: oqs_boringssl
    build: ./boringssl_client
    networks:
      - test-network
    volumes:
      - ./boringssl_client/ca/:/opt/tmp
