networks:
  test-network:
    driver: bridge
    attachable: true

services:
  classic_server:
    image: openquantumsafe/nginx
    hostname: classic.com
    ports:
      - "4433:4433"
    networks:
      - test-network
    volumes:
      - ./classic_server/certs/:/opt/nginx/pki
      - ./classic_server/config/:/opt/nginx/nginx-conf

  pq_server:
    image: openquantumsafe/nginx
    hostname: pq.com
    ports:
      - "4434:4434"
    networks:
      - test-network
    volumes:
      - ./pq_server/certs/:/opt/nginx/pki
      - ./pq_server/config/:/opt/nginx/nginx-conf

  hybrid_server:
    image: openquantumsafe/nginx
    hostname: hybrid.com
    ports:
      - "4435:4435"
    networks:
      - test-network
    volumes:
      - ./hybrid_server/certs/:/opt/nginx/pki
      - ./hybrid_server/config/:/opt/nginx/nginx-conf
  
  openssl_client:
    image: openquantumsafe/curl
    networks:
      - test-network
    volumes:
      - ./openssl_client/ca/:/opt/tmp
  
  boringssl_client:
    image: boringssl
    build: ./boringssl_client
    networks:
      - test-network
    volumes:
      - ./boringssl_client/ca/:/opt/tmp
