networks:
  proxy-network:
    driver: bridge
    attachable: true

services:
  proxy:
    image: openquantumsafe/httpd
    hostname: pqs_proxy.com
    user: root
    ports:
      - "4433:4433"
    networks:
      - proxy-network
    volumes:
      - ./proxy/certs/:/opt/httpd/pki
      - ./proxy/config/:/opt/httpd/httpd-conf
