networks:
  proxy-network:
    driver: bridge
    attachable: true

services:
  proxy:
    image: openquantumsafe/httpd
    hostname: pqProxy.com
    user: root
    ports:
      - "4433:4433"
    networks:
      - proxy-network
    volumes:
      - ./proxy/certs/:/opt/httpd/pki
      - ./proxy/config/:/opt/httpd/httpd-conf

  client:
    image: openquantumsafe/curl
    networks:
      - proxy-network
    volumes:
      - ./client/ca/:/opt/tmp
      - ./client/ca/oqs-bundle.pem:/opt/oqssa/oqs-bundle.pem
